/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGeminiChatRouteImport } from './routes/api/gemini-chat'
import { Route as ApiPushSendRemindersRouteImport } from './routes/api/push/send-reminders'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeminiChatRoute = ApiGeminiChatRouteImport.update({
  id: '/api/gemini-chat',
  path: '/api/gemini-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSendRemindersRoute = ApiPushSendRemindersRouteImport.update({
  id: '/api/push/send-reminders',
  path: '/api/push/send-reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/termos': typeof TermosRoute
  '/api/gemini-chat': typeof ApiGeminiChatRoute
  '/api/push/send-reminders': typeof ApiPushSendRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/termos': typeof TermosRoute
  '/api/gemini-chat': typeof ApiGeminiChatRoute
  '/api/push/send-reminders': typeof ApiPushSendRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/termos': typeof TermosRoute
  '/api/gemini-chat': typeof ApiGeminiChatRoute
  '/api/push/send-reminders': typeof ApiPushSendRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/termos'
    | '/api/gemini-chat'
    | '/api/push/send-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/termos'
    | '/api/gemini-chat'
    | '/api/push/send-reminders'
  id:
    | '__root__'
    | '/'
    | '/entrar'
    | '/termos'
    | '/api/gemini-chat'
    | '/api/push/send-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntrarRoute: typeof EntrarRoute
  TermosRoute: typeof TermosRoute
  ApiGeminiChatRoute: typeof ApiGeminiChatRoute
  ApiPushSendRemindersRoute: typeof ApiPushSendRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gemini-chat': {
      id: '/api/gemini-chat'
      path: '/api/gemini-chat'
      fullPath: '/api/gemini-chat'
      preLoaderRoute: typeof ApiGeminiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/send-reminders': {
      id: '/api/push/send-reminders'
      path: '/api/push/send-reminders'
      fullPath: '/api/push/send-reminders'
      preLoaderRoute: typeof ApiPushSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntrarRoute: EntrarRoute,
  TermosRoute: TermosRoute,
  ApiGeminiChatRoute: ApiGeminiChatRoute,
  ApiPushSendRemindersRoute: ApiPushSendRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
